# Generated by Django 4.1.5 on 2023-01-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('image_url', models.URLField()),
                ('base_experience', models.CharField(max_length=240, verbose_name='Name')),
                ('height', models.CharField(max_length=240, verbose_name='Name')),
                ('weight', models.CharField(max_length=240, verbose_name='Name')),
                ('abilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.ability')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.type')),
            ],
        ),
    ]
