# Generated by Django 4.1.5 on 2023-01-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_pokemon_poke_id_alter_pokemon_base_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='poke_id',
            field=models.IntegerField(default=-1),
        ),
    ]
