# Generated by Django 4.1.5 on 2023-01-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_alter_pokemon_poke_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='poke_id',
        ),
    ]
